### ISSUE TITLE
How about adding a gemspec file?

### ISSUE THREAD

**Issue by kojix2** [jamescook/libui-ruby#4]
I tried libui-ruby, but I was puzzled by the lack of a gemspec file. Maybe there is a reason why you didn't add gemspec, so I looked at your other project and it seems to have gemspec. Could you please add the gemspec file if you would? Thank you.

**Comment by kojix2** [comment]
I was going to contribute to libui-ruby to improve it, but I ended up thinking it would be faster to make it myself.

* https://github.com/kojix2/libui

libui is inspired by libui-ruby. Thank you very much.

**Comment by rubyFeedback** [comment]
I am trying to enhance "add-on" bindings to ruby-libui (not to be confused with libui-ruby :D) at https://www.rubydoc.info/gems/libui_paradise. Perhaps James may look into the old issue requests, have a look and then comment on pros/cons, in particular kojix2' ffi.rb solution.
